### ISSUE TITLE
Configuration broken since HH1.5.0-beta.1

### ISSUE THREAD

**Issue by st5000** [humhub-contrib/breakingnews#13] opened 2020-04-08 17:01 UTC
Getting this error when try to access on module configuration:

```
[error][yii\base\InvalidArgumentException] yii\base\InvalidArgumentException: The file or directory to be published does not exist: /opt/humhub/protected/humhub/modules/ui/form/resources in /opt/humhub/protected/vendor/yiisoft/yii2/web/AssetManager.php:455
Stack trace:
#0 /opt/humhub/protected/vendor/yiisoft/yii2/web/AssetBundle.php(185): yii\web\AssetManager->publish('/opt/xaronet_op...', Array)
#1 /opt/humhub/protected/vendor/yiisoft/yii2/web/AssetManager.php(266): yii\web\AssetBundle->publish(Object(humhub\components\AssetManager))
#2 /opt/humhub/protected/humhub/components/AssetManager.php(66): yii\web\AssetManager->loadBundle('humhub\\modules\\...', Array, true)
#3 /opt/humhub/protected/vendor/yiisoft/yii2/web/AssetManager.php(237): humhub\components\AssetManager->loadBundle('humhub\\modules\\...', Array, true)
#4 /opt/humhub/protected/vendor/yiisoft/yii2/web/View.php(287): yii\web\AssetManager->getBundle('humhub\\modules\\...')
#5 /opt/humhub/protected/humhub/modules/ui/view/components/View.php(169): yii\web\View->registerAssetBundle('humhub\\modules\\...', NULL)
#6 /opt/humhub/protected/vendor/yiisoft/yii2/web/AssetBundle.php(125): humhub\modules\ui\view\components\View->registerAssetBundle('humhub\\modules\\...')
#7 /opt/humhub/protected/humhub/widgets/views/markdownEditor.php(10): yii\web\AssetBundle::register(Object(humhub\modules\ui\view\components\View))
#8 /opt/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/opt/xaronet_op...')
#9 /opt/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/opt/xaronet_op...', Array)
#10 /opt/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/opt/xaronet_op...', Array, Object(humhub\widgets\MarkdownEditor))
#11 /opt/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('markdownEditor', Array, Object(humhub\widgets\MarkdownEditor))
#12 /opt/humhub/protected/humhub/widgets/MarkdownEditor.php(65): yii\base\Widget->render('markdownEditor', Array)
#13 /opt/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(140): humhub\widgets\MarkdownEditor->run()
#14 /opt/humhub/protected/modules/breakingnews/views/admin/index.php(27): yii\base\Widget::widget(Array)
#15 /opt/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/opt/xaronet_op...')
#16 /opt/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/opt/xaronet_op...', Array)
#17 /opt/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/opt/xaronet_op...', Array, Object(humhub\modules\breakingnews\controllers\AdminController))
#18 /opt/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(386): yii\base\View->render('index', Array, Object(humhub\modules\breakingnews\controllers\AdminController))
#19 /opt/humhub/protected/modules/breakingnews/controllers/AdminController.php(28): yii\base\Controller->render('index', Array)
#20 [internal function]: humhub\modules\breakingnews\controllers\AdminController->actionIndex()
#21 /opt/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /opt/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#23 /opt/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('index', Array)
#24 /opt/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('breakingnews/ad...', Array)
#25 /opt/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#26 /opt/humhub/index.php(25): yii\base\Application->run()
#27 {main}
```

**Comment by luke-** [comment] 2020-04-10 08:49
Can you try to reinstall the module?

I'm unable to reproduce this

**Comment by st5000** [comment] 2020-04-10 09:48
I tried, also checked file system permissions, error still the same.

**Comment by buddh4** [comment] 2020-04-11 19:46
Similar issue in the legal module: https://github.com/humhub-contrib/legal/issues/6 
So the directory `/opt/humhub/protected/humhub/modules/ui/form/resources` exists and contains following files: https://github.com/humhub/humhub/tree/develop/protected/humhub/modules/ui/form/resources ?

**Comment by st5000** [comment] 2020-04-12 07:54
No, `ressources` folder is missing.

HH 1.5.0-beta.1 was applied using web updater interface.

**Comment by buddh4** [comment] 2020-04-12 10:28
@luke- may an issue with the updater? The folder is part of the beta.1 package.

**Comment by luke-** [comment] 2020-04-14 13:49
It's was problem with the beta.1 upgrade package and will be fixed with the stable update.

**Closed by luke-** 2020-04-14 13:49 UTC
